// Contenido comercial aprobado. No contiene datos de una municipalidad.
export const diapositivas = [
  { titulo: "La documentación de su municipalidad, a mano", seccion: "Una gestión con respaldo", nota: "Abra con una situación cotidiana: alguien solicita el respaldo de un proyecto o de un pago. Pregunte cómo lo encuentran hoy. El valor de la propuesta es poder localizarlo y reunirlo con su contexto." },
  { titulo: "El costo de buscar lo que ya existe", seccion: "El problema", nota: "Estos son problemas posibles, no un diagnóstico de la municipalidad que escucha. Identifique cuál reconoce el equipo. No prometa porcentajes de ahorro: deben medirse durante la puesta en marcha." },
  { titulo: "Cada documento, en su contexto", seccion: "La solución", nota: "El archivo actual se centra en proyectos, obligaciones y pagos. La búsqueda usa registros y metadatos. No implica leer automáticamente todo el contenido de un PDF ni organizar el archivo completo de todas las dependencias." },
  { titulo: "Un expediente para cada consulta", seccion: "La respuesta", nota: "Los expedientes por proyecto reúnen requisitos y órdenes de pago. Por proveedor o período se reúnen los PDF de egresos filtrados. Un expediente completo por programa es una ampliación pendiente. La exportación no subsana documentos faltantes." },
  { titulo: "La revisión empieza en el trabajo diario", seccion: "Preparación para auditoría", nota: "La automatización abarca filtros, consulta, detección de ausencia de archivos y recopilación de PDF. El personal revisa la evidencia. No se emiten dictámenes ni se garantiza que una auditoría no tenga observaciones. La vista de auditoría actual no incluye ejecución presupuestaria." },
  { titulo: "Más tiempo para dar seguimiento", seccion: "Agilidad administrativa", nota: "La IA ayuda a redactar borradores, consultar datos y sugerir requisitos. No sustituye la revisión humana. Proyectos incluye preparación documental y orden de inicio, no estudios de factibilidad ni diseños. SAMI tiene equivalencias y conversión desde reportes SAFT, no sincronización automática directa." },
  { titulo: "Una puesta en marcha acompañada", seccion: "Implementación", nota: "El alcance incluye configuración, carga acotada de archivos organizados, capacitación y validación. Antes de activar cada instalación hay que verificar separación de datos, permisos y recuperación de archivos. No prometer una política de respaldo o disponibilidad que no se haya contratado y probado." },
  { titulo: "Una inversión clara para su municipalidad", seccion: "Propuesta económica", nota: "Precios preliminares en lempiras, antes de impuestos y sujetos a diagnóstico. Recomendado: L 50,000 de implementación y L 9,000 mensuales; L 158,000 el primer año. No incluye cesión del código fuente. Soporte en horario laboral. Digitalización física, integraciones y desarrollos nuevos se cotizan aparte. No hay atención 24/7 ni consumo ilimitado." },
] as const;

export const planes = [
  { nombre: "Archivo y expedientes", implementacion: "30,000", mensual: "6,000", usuarios: "10 usuarios", almacenamiento: "25 GB", carga: "500 PDF", capacitacion: "4 h", soporte: "3 h / mes", descripcion: "Organización de respaldos y preparación de expedientes.", recomendado: false },
  { nombre: "Documentación y control", implementacion: "50,000", mensual: "9,000", usuarios: "25 usuarios", almacenamiento: "75 GB", carga: "1,500 PDF", capacitacion: "8 h", soporte: "5 h / mes", descripcion: "Documentos conectados con proyectos y seguimiento financiero.", recomendado: true },
  { nombre: "Acompañamiento ampliado", implementacion: "80,000", mensual: "14,000", usuarios: "50 usuarios", almacenamiento: "150 GB", carga: "3,000 PDF", capacitacion: "12 h", soporte: "8 h / mes", descripcion: "Mayor alcance entre áreas y seguimiento mensual de adopción.", recomendado: false },
] as const;
